version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env.prod
    ports:
      - 2222:2222
      - "${IMGS_SSH_V4:-22}:2222"
      - "${IMGS_SSH_V6:-[::1]:22}:2222"
  registry:
    image: registry
    volumes:
      - ./data/registry:/var/lib/registry
